### ISSUE TITLE
[共通]パス指定周りの見直し(js)

### ISSUE THREAD

**Issue by KARASU-2000** [NT-Dentsu/dentsuTools#110]
# ToDo
動作上は問題ないが
- Javascriptの全ファイルを対象に、パス指定の方法(相対パス→絶対パス)に変更する

**Comment by towa1204** [comment]
@KARASU-2000 
これって文字通りjavascriptファイルに書かれてあるurlを書き換えるということ？
それともhtmlファイルのscriptタグに指定しているjavascriptファイルのurlを書き換えるということ？

**Comment by KARASU-2000** [comment]
前者(jsファイルのURL書き換え)でお願いします！
量が多そうなので、HTMLは別でIssue立てて対応した方がよさげかも
