### ISSUE TITLE
[パネルカスタマイズ画面]データベースアクセスのアウトソーシング

### ISSUE THREAD

**Issue by NumLock810** [NT-Dentsu/dentsuTools#119]
issue #115 のPHPまわりの処理を丸投げします

- [x] ユーザーIDを取得する関数
- [x] ユーザーパネル情報テーブルから指定したユーザーIDのパネル情報を取得する関数
- [x] 連想配列を与えてユーザーパネル情報テーブルを更新する関数
- [x]  m_panelテーブルからpanel_nameを取得する関数(php, js)
- [x] アカウント作成時にt_user_panel_infoにアンカー番号0~15までのレコード作成

下二つはユーザーID指定部分をなくしてしまってもいいかも(関数内でID取得する的な)
データの形はできれば連想配列が良いです

**Comment by towa1204** [comment]
連想配列というのは、keyがパネル名でvalueに配列[アンカー番号, パネルサイズ]の配列ということ？
あと、格納するときはどのようにパネル関連のデータを渡したいかも明確にしてほしい

**Comment by NumLock810** [comment]
欲しい情報が，
・パネル名
・パネルの位置(アンカー番号)
・パネルサイズ
・画像のリンク
・ツールのリンク
の5つ
これを連想配列(変数名info(仮))で欲しい
パネルの数だけinfoが必要だから，実際に受け渡すデータはinfoの配列になる
infoの配列自体は重複さえなければ順番は問わない
って感じです
DBへの格納時は引数にinfoの配列を渡すようにする
DBからの取得時も引数に渡す形にして，返り値を処理の成否とかにするといい感じかもしれない

**Comment by NumLock810** [comment]
以下の情報は，「パネル名」「パネル位置」「パネルサイズ」「画像リンク」「ツールリンク」の順

```
1. "size M hol",   0,   4,  "image_panel_M_h.jpg",   "./panel_sample/panel_sample.html"
2. "size S",       2,   5,  "image_panel_S.jpg",     "./panel_sample/panel_sample.html"
3. "size M var",   3,   3,  "image_panel_M_v.jpg",   "./panel_sample/panel_sample.html"
4. "size L",       4,   2,  "image_panel_L.jpg",     "./panel_sample/panel_sample.html"
5. "size M var",   6,   3,  "image_panel_M_v.jpg",   "./panel_sample/panel_sample.html"
6. "size S",      11,   5,  "image_panel_S.jpg",     "./panel_sample/panel_sample.html"
7. "size S",      12,   5,  "image_panel_S.jpg",     "./panel_sample/panel_sample.html"
8. "size M hol",  13,   4,  "image_panel_M_h.jpg",   "./panel_sample/panel_sample.html"
9. "size S",      15,   5,  "image_panel_S.jpg",     "./panel_sample/panel_sample.html"
```


![panel_layout_intro](https://user-images.githubusercontent.com/71932961/133888294-1945a86a-5dc8-42c5-88f9-363877608890.png)

**Comment by towa1204** [comment]
上の例だと、主キーのパネルネームが重複するからレコードの登録できなくない？

**Comment by NumLock810** [comment]
[こ↑こ↓](https://scrapbox.io/NT-Dentsu/2021/06/26(%E5%9C%9F)%E3%80%80%E8%AD%B0%E4%BA%8B%E9%8C%B2)で一応主キー修正について言及してる
で，issueのDB定義修正3で修正するはずなので，たぶん恐らくなんとなく大丈夫

**Comment by towa1204** [comment]
おｋ
なんかテーブルの構成に違和感感じる
m_panelの構成だと、パネルネームが等しいときは、リンク先・表示する画像はいつでも同じになってしまうけど大丈夫？

**Comment by NumLock810** [comment]
わかりにくいけど，パネルネーム≒コンテンツ名 みたいな感じ
いまはパネルサイズをそのままパネルネームとして流用してるけど，実際はパネルネームにはリンク先のコンテンツ名を設定する感じ．
そもそもパネルネームはaltタグで表示する用に設定してるからね

**Comment by towa1204** [comment]
なるほど、パネルネームについてはわかった。
t_user_panel_infoのアンカー番号を主キーに加えることについては、パネル画面上に同じパネルネームのパネルを複数置きたいってこと？
あと、パネルネームは外部キーのほうがいいかもね（多分）

**Comment by NumLock810** [comment]
いわれてみると，アンカー番号が決して重複しないっていう前提なら主キーはユーザーIDとアンカー番号だけでいい気がしてきた．
今度DB担当者に掛け合ってみますね
同じパネルネーム云々はそのとおり

**Comment by KARASU-2000** [comment]
メール来てたから内容確認した
主キーに関しては、確かにユーザーIDとアンカー番号がいいね(カスタマイズ時に主キーをUPDATEなんてしたくないし)

**Comment by KARASU-2000** [comment]
あ、もう一つあったか。
テーブルに外部キー制約つける件は、土曜日に相談させてくだせえ。

**Comment by NumLock810** [comment]
パネル情報のDB操作の云々

・主キーは変更しない
・パネル名とコンテンツがnullになることがある
・更新する際は，指定していないアンカー番号のパネル名とコンテンツは全てnullにする

**Comment by towa1204** [comment]
>指定していないアンカー番号のパネル名とコンテンツは全てnullにする

ってコンテンツはパネルサイズの間違いじゃない？

**Comment by NumLock810** [comment]
...ﾊｲ
ﾓｼｬﾓｼｬｾﾝ

**Comment by towa1204** [comment]
アンカー番号の範囲って0からいくつまで?

**Comment by NumLock810** [comment]
とりあえず 15 で

**Comment by towa1204** [comment]
追加実装

- [x] m_panelテーブルからpanel_nameを取得する関数(php, js)
- [x] アカウント作成時にt_user_panel_infoにアンカー番号0~15までのレコード作成
