### ISSUE TITLE
[メイン画面]KindleCopy中の非推奨となったdocument.execCommand("copy")を置き換える

### ISSUE THREAD

**Issue by towa1204** [NT-Dentsu/dentsuTools#165]
`index/app/kindle_copy/kindle_copy.js`中のクリップボードにコピーする処理`document.execCommand("copy")`が非推奨となっているため置き換える。

https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand
![image](https://user-images.githubusercontent.com/24364250/151648747-2a4e51a5-bf13-432d-b04d-3b6748f537c0.png)

**Comment by KARASU-2000** [comment]
サーバにデプロイして動かすと、「Cannot read property ‘writeText’ of undefined」エラーになるため、本Issueは対応せずにクローズ
