### ISSUE TITLE
[パネルカスタマイズ画面]パネルカスタマイズ機能の実装その3-2　パネル配置を変更可能にする

### ISSUE THREAD

**Issue by NumLock810** [NT-Dentsu/dentsuTools#167]
パネル配置を変更可能にする

詳細な仕様はまだ考え中
暫定的な仕様として
・パネルが重なったら以前のパネルを消去
・ドラッグアンドドロップで設定可能にする
・各パネルデータは可能ならデータベースからとってくる
・パネルの境界部分には配置できないようにする

**Comment by KARASU-2000** [comment]
> ・パネルの境界部分には配置できないようにする
![image](https://user-images.githubusercontent.com/60570891/151660276-819a626c-b511-4eeb-91ff-61358cf07d3c.png)
