### ISSUE TITLE
[パネルカスタマイズ画面]共有のCSSが読み込めない

### ISSUE THREAD

**Issue by KARASU-2000** [NT-Dentsu/dentsuTools#171]
# 現象
パネルカスタマイズ画面でルートディレクトリ直下のCSSが読み込めず、ダッシュボードのレイアウトが反映されない
- パネルカスタマイズ画面
![image](https://user-images.githubusercontent.com/60570891/152555332-c7931069-09f9-4ee8-b0cb-10d48c97b56c.png)
- その他の画面
![image](https://user-images.githubusercontent.com/60570891/152555448-d58fdb7e-b768-49f8-ae44-eb7a4e460538.png)

# 再現手順
- パネルカスタマイズ画面に遷移する

# 発生頻度
- 必ず発生する

**Comment by NumLock810** [comment]
原因：common/titileber.phpの15行目において読み込むphpを相対アドレスで指定しているため，パスが通っていない
対策：アドレス指定を絶対アドレスにする．ただし，この部分は issue #174 とかぶるためそちらでの対処が望ましい(訳：めんどくさいからそっちでやって)

**Comment by towa1204** [comment]
#174 でやります（解決します）
