### ISSUE TITLE
[共通]パス指定周りの見直し(php)

### ISSUE THREAD

**Issue by KARASU-2000** [NT-Dentsu/dentsuTools#174]
# 概要
- #110 の類似のIssue
- 対象はPHP(DOCUMENT_ROOTのパスをくっつけて、絶対パスで指定する)

**Comment by NumLock810** [comment]
ついでにcommon配下のphpも一つのフォルダにまとめて欲しいです

**Comment by towa1204** [comment]
@bot810 
ここも絶対パスにしたほうがいいですかね...?
https://github.com/NT-Dentsu/dentsuTools/blob/88005785aef3bde8ae2026a21ed13b940c376ac7/index/panel_customize/panel_customize.php#L84-L86

**Comment by NumLock810** [comment]
全部絶対パスで統一してくださ
