### ISSUE TITLE
[パネルカスタマイズ画面]DBのm_panelテーブルからレコードを取ってくる関数を作る

### ISSUE THREAD

**Issue by NumLock810** [NT-Dentsu/dentsuTools#184]
m_panelテーブルからデータを取ってくる関数が欲しい

仕様
- m_panelテーブルからデータを取ってくる
- jsで利用できる関数として実装
- 引数は無し
- 返り値としてカラム名をキーとした連想配列の配列
- 一回の呼び出しですべてのレコードのデータを持って来る

**Comment by towa1204** [comment]
なんのデータかわからないです...

**Comment by towa1204** [comment]
php, js部分ともに作る
