### ISSUE TITLE
[共通]index.php以外でユーザアイコンの表示がおかしい

### ISSUE THREAD

**Issue by towa1204** [NT-Dentsu/dentsuTools#189]
# バグの例
![Screenshot from 2022-04-14 16-02-13](https://user-images.githubusercontent.com/24364250/163331769-2e80782b-039f-4580-ab4a-d167949700fe.png)
![Screenshot from 2022-04-14 16-03-32](https://user-images.githubusercontent.com/24364250/163331936-eb2ea5f5-a29d-42c4-a92b-9b0a6d64e2e2.png)

# 原因
ユーザアイコンのサイズなどを調整するCSS(`/user_icon/css/user_icon.css`)を読み込んでいるのは`index.php`だけであるため。
![Screenshot from 2022-04-14 16-06-15](https://user-images.githubusercontent.com/24364250/163332686-4c00f721-afa6-4a34-bb1d-c8c5fe1972c1.png)

# 対処法
`user_icon.php`に入れるべき？

**Comment by towa1204** [comment]
#190 がマージされたらやる

**Comment by bot810** [comment]
#171 と同様のissueなのでどちらかにまとめるべき？

**Comment by towa1204** [comment]
ユーザアイコンを含んでいるタイトルバーはindex.php以外にも使われるが、ユーザアイコンのcssがindex.phpしかない

**Comment by towa1204** [comment]
cssの部分を直したら、次は`panel_customize.php`と`kindle_copy.php`に限ってuser_iconの`プロフィール`と`ログイン`が**最初から**露出してしまっている。
![image](https://user-images.githubusercontent.com/24364250/173193010-4f6deb31-44a5-4c09-b4a3-e8dbc0c55d2f.png)
![image](https://user-images.githubusercontent.com/24364250/173193038-1adeaeb1-7244-4aff-89b7-2d0f11e0c683.png)

### 原因
`user_icon_click.js`(user_iconの`プロフィール`と`ログイン`の表示を表示したり隠したりする機能)がjQueryのCDNより先に読み込まれてしまっているため。

### 解決策
2つのうちのいずれか
* `user_icon.php`で読み込まれているjsファイルを各phpファイルに配置する
* `panel_customize.php`と`kindle_copy.php`でjQueryのCDNを先に読み込むようにする。

**Comment by towa1204** [comment]
jQuery(Bootstrap)のCDNを最初に読み込むようにする
すべてHeadタグに持っていく
