### ISSUE TITLE
[パネルカスタマイズ画面]キャンセルボタンが効かないバグ再発

### ISSUE THREAD

**Issue by KARASU-2000** [NT-Dentsu/dentsuTools#192]
# 発生している現象

* #181 のバグが再発したため修正を行う

# 原因

* #181 と原因は同様
* 変数panelInfoをglobalにした際にキャンセルボタンイベントでの使用部分だけ修正漏れしたため発生

# 追記

* #182 のバグが併発しているため動作確認が困難，先にそちらのマージが必要(かもぉ)

**Comment by towa1204** [comment]
キャンセル後にsetボタン押すと、意図しない動作をするバグがある（#196 参照）
このバグを解消することで解決する可能性がある
