### ISSUE TITLE
[共通]サイドバー・タイトルバーのスタイル崩れ

### ISSUE THREAD

**Issue by KARASU-2000** [NT-Dentsu/dentsuTools#206]
# 現象

- プロフィール画面・KindleCopyで、サイドバー・タイトルバーのスタイルが崩れている
    - 正しい表示
![image](https://user-images.githubusercontent.com/60570891/175801681-80b0e057-dd2d-433b-9c74-29dfc1d61c63.png)
    - スタイル崩れ
![image](https://user-images.githubusercontent.com/60570891/175801692-85e353d2-42ab-40c6-bad0-5ea2d9bca48f.png)

---

# 再現手順

- 必ず発生する

---

# 原因

- dashboard.cssのパスが間違っている(#130 の対応漏れと思われる)

**Comment by towa1204** [comment]
![image](https://user-images.githubusercontent.com/24364250/178125601-424c506f-f947-457d-89dc-de51a8b87fca.png)

`settings.js`と`dashboard.css`のパスを正しく修正する必要がある。
