### ISSUE TITLE
[メイン画面]ホーム画面とカスタマイズ画面で共通するcss, jsをまとめる

### ISSUE THREAD

**Issue by bot810** [NT-Dentsu/dentsuTools#42]
ホーム画面とカスタマイズ画面で共通するcssファイルやjsファイルがあるため，これをまとめる
まとめるときは，より上位のディレクトリにする

# ToDo

- [ ] cssファイルをまとめる
- [ ] jsファイルをまとめる

**Comment by NumLock810** [comment]
#97 とかぶってたのでクローズします
