### ISSUE TITLE
[メイン画面]NT-dentsuの部分にホーム画面へのリンクを張る

### ISSUE THREAD

**Issue by bot810** [NT-Dentsu/dentsuTools#51]
# ToDo

- [ ] ページ左上のNT-dentsuにホーム画面へのリンクを張る

**Comment by KARASU-2000** [comment]
![image](https://user-images.githubusercontent.com/60570891/128632382-e28e0153-25d4-47d7-8798-cf637f9ea01c.png)
画像の赤枠の箇所って認識だけど、間違いない？
動作とソースを見る限り、既に実装済みと思う。

**Comment by NumLock810** [comment]
そこであってるけど，実装はされてなくない？

**Comment by KARASU-2000** [comment]
![image](https://user-images.githubusercontent.com/60570891/128665933-721ff05e-e4b2-45c5-b613-4b40fc5cf5e3.png)
これは違うの？
…って思ったけど、どうやらtowa君が、サイドバーとかのモジュール化するときに実装してたっぽい(https://github.com/NT-Dentsu/dentsuTools/pull/99)
最新のdevelopブランチをプルして動作見て問題なかったら、このIssueを閉じていただきたく

**Comment by NumLock810** [comment]
ちゃんと動くようなのでissue閉じます
