### ISSUE TITLE
[ログイン画面]パス指定の修正(相対パス→絶対パス)

### ISSUE THREAD

**Issue by KARASU-2000** [NT-Dentsu/dentsuTools#68]
# ToDo
- パス指定を相対パスで行っているため、絶対パスとなるように修正する。
→参考:https://scrapbox.io/NT-Dentsu/%E7%B5%B6%E5%AF%BE%E3%83%91%E3%82%B9%E3%81%AE%E6%8C%87%E5%AE%9A%E6%96%B9%E6%B3%95

- [x] サーバー側修正
- [x] クライアント側修正

**Comment by towa1204** [comment]
担当します
